apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "_labels" . | indent 4 }}
  name: frontend-deployment
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "_labels" . | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "_labels" . | indent 8 }}
    spec:
      containers:
      - name: nginx
        image: {{ .Values.image }}
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
