apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "_labels" . | indent 4 }}
  name: frontend-service
spec:
  ports:
  - name: http
    port: 80
  selector:
    {{- include "_labels" . | indent 4 }}
